local _0x9f8a=exports['qb-core']:GetCoreObject();_0x9f8a.Functions.CreateUseableItem('prop_bagcat_chill',function(_0x0001,_0x0002)local _0x0003=_0x9f8a.Functions.GetPlayer(_0x0001)TriggerClientEvent('sal24k:prop_bagcat_chill',_0x0001)end);_0x9f8a.Functions.CreateUseableItem('prop_newplay',function(_0x0004,_0x0005)local _0x0006=_0x9f8a.Functions.GetPlayer(_0x0004)TriggerClientEvent('sal24k:propnewplay',_0x0004)end);_0x9f8a.Functions.CreateUseableItem('noone_cuteghosts_anim_fashions',function(_0x0007,_0x0008)local _0x0009=_0x9f8a.Functions.GetPlayer(_0x0007)TriggerClientEvent('sal24k:noone_cuteghosts_anim_fashions',_0x0007)end);local _0x1ff3={[[$$$$$$\   $$$$$$\  $$\              $$$$$$\  $$\   $$\ $$\   $$\ $$$  __$$\ $$  __$$\ $$ |            $$  __$$\ $$ |  $$ |$$ | $$  |$$ /  \__|$$ /  $$ |$$ |            \__/  $$ |$$ |  $$ |$$ |$$  / \$$$$$$\  $$$$$$$$ |$$ |             $$$$$$  |$$$$$$$$ |$$$$$  /   \____$$\ $$  __$$ |$$ |            $$  ____/ \_____$$ |$$  $$<   $$$\   $$ |$$ |  $$ |$$ |            $$ |            $$ |$$ |\$$\ \$$$$$$  |$$ |  $$ |$$$$$$$$\       $$$$$$$$\       $$ |$$ | \$$\  \______/ \__|  \__|\________|      \________|      \__|\__|  \__|]],[[ $$$$$$\   $$$$$$\  $$\              $$$$$$\  $$\   $$\ $$\   $$\ $$$  __$$\ $$  __$$\ $$ |            $$  __$$\ $$ |  $$ |$$ | $$  |$$ /  \__|$$ /  $$ |$$ |            \__/  $$ |$$ |  $$ |$$ |$$  / \$$$$$$\  $$$$$$$$ |$$ |             $$$$$$  |$$$$$$$$ |$$$$$  /   \____$$\ $$  __$$ |$$ |            $$  ____/ \_____$$ |$$  $$<   $$$\   $$ |$$ |  $$ |$$ |            $$ |            $$ |$$ |\$$\ \$$$$$$  |$$ |  $$ |$$$$$$$$\       $$$$$$$$\       $$ |$$ | \$$\  \______/ \__|  \__|\________|      \________|      \__|\__|  \__|]]}function _0x2ef2()print("\027[H\027[2J")local _0x000a=1;local _0x000b,_0x000c=#_0x1ff3,GetGameTimer()+1200;local function _0x000d()if GetGameTimer()<_0x000c then print(_0x1ff3[_0x000a])_0x000a=_0x000a%_0x000b+1;Citizen.Wait(500)print("\027[H\027[2J")_0x000d()end end _0x000d()end AddEventHandler('onResourceStart',function(_0x000e)if GetCurrentResourceName()==_0x000e then _0x2ef2()end end)

-- 
--  $$$$$$\   $$$$$$\  $$\              $$$$$$\  $$\   $$\ $$\   $$\ 
-- $$  __$$\ $$  __$$\ $$ |            $$  __$$\ $$ |  $$ |$$ | $$  |
-- $$ /  \__|$$ /  $$ |$$ |            \__/  $$ |$$ |  $$ |$$ |$$  / 
-- \$$$$$$\  $$$$$$$$ |$$ |             $$$$$$  |$$$$$$$$ |$$$$$  /  
--  \____$$\ $$  __$$ |$$ |            $$  ____/ \_____$$ |$$  $$<   
-- $$\   $$ |$$ |  $$ |$$ |            $$ |            $$ |$$ |\$$\  
-- \$$$$$$  |$$ |  $$ |$$$$$$$$\       $$$$$$$$\       $$ |$$ | \$$\ 
--  \______/ \__|  \__|\________|      \________|      \__|\__|  \__|